index:
   path: /
   controller: App\Controller\UserController::index
create:
   path: /create
   controller: App\Controller\UserController::create
store:
   path: /store
   controller: App\Controller\UserController::store
   methods: ["POST"]
signIn:
   path: /auth/signIn
   controller: App\Controller\AuthController::signIn
   methods: []