# Main page routes
home:
   path: /
   controller: App\Controller\HomeController::index

# Users routes
users__index:
   path: /users
   controller: App\Controller\UserController::index
   
# Auth routes
signIn:
   path: /auth/signIn
   controller: App\Controller\AuthController::signIn
   methods: ["GET", "POST"]
signUp:
   path: /auth/signUp
   controller: App\Controller\AuthController::signUp
   methods: ["GET", "POST"]